import VerticalNavbar from "@/components/verticalnavbar";
import Navbar from "@/components/navbar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "../../styles/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
        </div>
        <div className="flex w-screen bg-gray-100">
          <VerticalNavbar />
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
